Fixed GetRoomById Endpoint to return proper room (not first found).
high-engineers/SmartHome pull request #14
Opened 2019-11-16 14:17 UTC by johnnythemadman

2019-11-16 21:26 UTC, Snooking requested changes

2019-11-16 21:26 UTC, Snooking commented on server/SmartHome.BusinessLogic/Components/CommandHandlers/SwitchDeviceCommandHandler.cs
> +        private readonly DeviceExistsValidationRule _deviceExistsValidationRule;
Missing device is in room validation rule

2019-11-16 21:26 UTC, Snooking commented on server/SmartHome.API/Rooms/RoomsController.cs
> +        public async Task<IActionResult> SwitchDevice([FromQuery] UserIdSmartHomeEntityIdQueryParam queryParam, [FromRoute] Guid roomId, [FromRoute] Guid componentId, [FromQuery] bool isOn)
isOn is not a proper name. I have no idea whether I'm supposed to give You current state or the desired state

2019-11-16 21:26 UTC, Snooking commented on server/SmartHome.API/Infrastructure/UserIdSmartHomeEntityIdQueryParam.cs
> +        public Guid UserId { get; set; }
Please change the name to `RequestedByUserId`. Later, when we'll add changing other users permissions, we will have name conflict, so let's come prepared

2019-11-16 21:33 UTC, johnnythemadman commented on server/SmartHome.API/Rooms/RoomsController.cs
> +        public async Task<IActionResult> SwitchDevice([FromQuery] UserIdSmartHomeEntityIdQueryParam queryParam, [FromRoute] Guid roomId, [FromRoute] Guid componentId, [FromQuery] bool isOn)
I just follow endpoint document XD

2019-11-16 23:22 UTC, johnnythemadman commented on server/SmartHome.BusinessLogic/Components/CommandHandlers/SwitchDeviceCommandHandler.cs
> +        private readonly DeviceExistsValidationRule _deviceExistsValidationRule;
done

2019-11-16 23:22 UTC, johnnythemadman commented on server/SmartHome.API/Rooms/RoomsController.cs
> +        public async Task<IActionResult> SwitchDevice([FromQuery] UserIdSmartHomeEntityIdQueryParam queryParam, [FromRoute] Guid roomId, [FromRoute] Guid componentId, [FromQuery] bool isOn)
changed to newState, i believe you will like it ;) also modified endpoint document

2019-11-16 23:23 UTC, johnnythemadman commented on server/SmartHome.API/Infrastructure/UserIdSmartHomeEntityIdQueryParam.cs
> +        public Guid UserId { get; set; }
yep, done

2019-11-17 13:55 UTC, Snooking approved these changes

2019-11-17 14:55 UTC, merged